title: "JASQAI â€“ Journal of Agentic Synergy & Quantum AI"
description: "A journal for Agentic AI, Quantum AI, FinTech, Algorithms, Mathematics & Statistics."
markdown: kramdown
theme: minima
plugins: []
